version: 2
updates:
  # Configuration for JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/" # Root directory
    schedule:
      interval: "daily"

  # Configuration for PHP dependencies
  - package-ecosystem: "composer"
    directory: "/" # Root directory
    schedule:
      interval: "daily"
