version: '3'
services:

    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./scripts/docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/opt/una
        networks:
            unanet:
                aliases:
                    - localhost.una.io

    php:
        build:
            context: .
            dockerfile: scripts/docker-compose/PHP.Dockerfile
        volumes:
            - ./scripts/docker-compose/php.ini:/usr/local/etc/php/php.ini
            - ./:/opt/una
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - unanet

    cron:
        build:
            context: .
            dockerfile: scripts/docker-compose/Cron.Dockerfile
        volumes:
            - ./scripts/docker-compose/php.ini:/usr/local/etc/php/php-cron.ini
            - ./:/opt/una
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - unanet

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'una'
            MYSQL_PASSWORD: 'una'
            MYSQL_DATABASE: 'una'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./scripts/docker-compose/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
            - ./scripts/docker-compose/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
        ports:
            - 3306:3306
        networks:
            - unanet

    jot:
        image: unaio/jot-server:latest
        restart: always
        ports:
            - 5555:5000
        networks:
            - unanet

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - UPLOAD_LIMIT=200M
        volumes:
            - ./scripts/docker-compose/phpmyadmin.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
            - mysql
        networks:
            - unanet

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - unanet

volumes:
    mysqldata: {}

networks:
  unanet:
